input { stdin { } }
filter {
  script {
    code => "
      ctx._source.msg_length = ctx._source.message.length();
      if (ctx._source.message.contains(\"GET\")) { ctx._source.method = \"GET\"; ctx._source.is_read = true } else { ctx._source.is_read = false }
      ctx._source.processed = true
    "
  }
}
output { null { } }
