input { stdin { } }
filter { grok { match => { "message" => "%{IPORHOST:client_ip} %{WORD:method} %{URIPATH:path} %{INT:status:int} %{INT:bytes:int} %{QS:agent} %{NUMBER:latency:float}" } } }
output { null { } }
