#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# 90-marketplace-finalise.sh -- last-mile preparation of the AMI for
# Marketplace submission.
#
# This script runs LAST, after all hardening + product wiring is done, and
# immediately before Packer powers off the build VM. It removes the SSH host
# keys and the ec2-user/root authorized_keys, so it MUST be the final stage:
# any later provisioner that needed the SSH session would break.
#
# Compliance gates implemented (cross-referenced to the AWS Marketplace AMI
# listing documentation):
#
#   1. /etc/aws-marketplace/productcode populated with the seller's product code.
#   2. SSH host keys removed -- regenerated by `sshd-keygen.service` on first
#      boot so every buyer instance gets unique keys.
#   3. ec2-user `~/.ssh/authorized_keys` removed (no baked-in SSH keys).
#   4. Bash history and audit logs scrubbed across `root` and `ec2-user`.
#   5. Cloud-init artefacts cleaned so the next boot re-runs cloud-init with
#      the buyer's user-data.
#   6. dnf cache cleared.
#   7. /tmp scrubbed.

set -euo pipefail

# Inputs are surfaced as environment variables by the Packer
# `provisioner "shell" { environment_vars = ... }` block.
readonly PRODUCT_CODE="${FERROSTASH_PRODUCT_CODE:-REPLACE-WITH-SELLER-PRODUCT-CODE}"
readonly FS_VER="${FERROSTASH_VERSION:-unknown}"

# 1. Marketplace productcode --------------------------------------------
install -d -m 0755 /etc/aws-marketplace
cat >/etc/aws-marketplace/productcode <<EOF
${PRODUCT_CODE}
EOF
chmod 0644 /etc/aws-marketplace/productcode

cat >/etc/aws-marketplace/ferro-stash-version <<EOF
${FS_VER}
EOF
chmod 0644 /etc/aws-marketplace/ferro-stash-version

# 2. SSH host keys -- regenerated on first boot -------------------------
# AL2023 ships `sshd-keygen.service` (oneshot) which auto-generates the host
# keys when missing. Removing them here forces fresh keys per buyer instance.
shopt -s nullglob
for keyfile in /etc/ssh/ssh_host_*; do
    rm -f "${keyfile}"
done
shopt -u nullglob

# 3. ec2-user authorized_keys ------------------------------------------
if [[ -d /home/ec2-user/.ssh ]]; then
    rm -f /home/ec2-user/.ssh/authorized_keys
fi
if [[ -d /root/.ssh ]]; then
    rm -f /root/.ssh/authorized_keys
fi

# 4. History + audit log scrub -----------------------------------------
for histfile in \
    /root/.bash_history \
    /root/.zsh_history \
    /root/.lesshst \
    /root/.viminfo \
    /home/ec2-user/.bash_history \
    /home/ec2-user/.zsh_history \
    /home/ec2-user/.lesshst \
    /home/ec2-user/.viminfo; do
    if [[ -f "${histfile}" ]]; then
        : >"${histfile}"
    fi
done

# Truncate (do not delete) audit logs -- preserves ownership / selinux context
# and makes the next-boot delta auditable.
if [[ -f /var/log/audit/audit.log ]]; then
    : >/var/log/audit/audit.log
fi
for log in /var/log/secure /var/log/messages /var/log/cron /var/log/maillog; do
    if [[ -f "${log}" ]]; then
        : >"${log}"
    fi
done
# Also rotate + vacuum journald so the AMI doesn't carry build-time logs.
journalctl --rotate || true
journalctl --vacuum-time=1s || true

# 5. cloud-init scrub --------------------------------------------------
if command -v cloud-init >/dev/null 2>&1; then
    cloud-init clean --logs --seed || true
fi

# 6. dnf cache scrub ---------------------------------------------------
dnf clean all
rm -rf /var/cache/dnf

# 7. /tmp scrub --------------------------------------------------------
find /tmp -mindepth 1 -maxdepth 1 -exec rm -rf {} +

echo "[90-marketplace-finalise] AMI is Marketplace-ready (productCode=${PRODUCT_CODE}, version=${FS_VER})."
